### ISSUE TITLE
Missing dependencies in clean environment

### ISSUE THREAD

**Issue by gassmoeller** [mrempel/geohexviz#1]
When installing geohexviz using pip into a clean conda environment (build from environment.yml) the dependency `pdfCropMargins` is missing (it seems it is only available from pypi, so would need to be added to setup.py?).

**Comment by gassmoeller** [comment]
Related to openjournals/joss-reviews#5073

**Comment by gassmoeller** [comment]
Oh, I see now that `pdfCropMargins` is part of the development environment file. However I think that should be moved over to the regular environment file, it is needed for executing the examples even without developing the software itself.

**Comment by mrempel** [comment]
Tony -

Before we make any more changes, I would like to get it accepted by the
journal and published. Continuing developing (or changing the repository)
outside the peer review process means that the repository that is being
reviewed is changing and this may be confusing / annoying for the reviewers.

I merged the buffer branch into master and am just waiting for the actions
to complete.

Mark

**Comment by mrempel** [comment]
We have modified the environment.yml and setup.py files so that pdfcropmargins is part of the standard install of geohexviz. In addition, we have updated the README.rst file so that it no longer states a special install instruction is required for pdfcropmargins.
