### ISSUE TITLE
Examples require changes to file names before they run successfully

### ISSUE THREAD

**Issue by gassmoeller** [mrempel/geohexviz#3]
Related to https://github.com/openjournals/joss-reviews/issues/5073

The paths to data files and output files in the examples are currently placeholder values. I understand that you want to point out the places to users where they have to adjust things for their application. However, in the current form that means that the first thing new users see of your software is an error message (not the great figures that the examples produce). I could see a place for template values in the jupyter notebooks (where it is immediately clear what needs to be changed, but especially in the JSON and python scripts this choice seems not intuitive. Would it make sense to change them to the (existing) data files and output files in the respective folders, so that the example results are easier to reproduce? You could still leave a comment that indicates these are the places to change for user applications.

**Comment by mrempel** [comment]
We have modified the examples such that the file placeholders have been replaced with the actual files to be called to execute the examples. For example, when a user executes `python python_walkthrough.py` in the forest_fire example directory, the corresponding visualization will be created as expected. This has also be done for the .md files and notebooks resident in the example directories.
