### ISSUE TITLE
Enable user to install from PyPI

### ISSUE THREAD

**Issue by tony-zeidan** [mrempel/geohexviz#5]
Should we let the user install the package from PyPI?
Recall the reason why our project is conda-based (for lack of a better term) is because installing the GeoPandas dependency via pip is an issue on some operating systems (most notably Windows). 
I believe this is a must because it allows for flexibility - those who install GeoPandas using the combination of pip and pre-compiled binaries to also install geohexviz easily.

**Comment by mrempel** [comment]
GeoHexViz has been pushed to PyPI. The install instructions in the README.rst file have been updated to inform a user how to install GeoHexViz from PyPI (option 1) and GitHub (option 2).
